name: blood_camp_finder_project
description: "Blood Camp Finder"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.30.0
  firebase_auth: ^4.17.4
  firebase_auth_mocks: ^0.13.0
  firebase_core_web: ^2.17.5
  cloud_firestore: ^4.15.3
  shared_preferences: ^2.2.2
  permission_handler: ^12.0.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator: ^11.0.0
  url_launcher: ^6.3.2
  ini: ^2.1.0
  intl: ^0.18.1
  connectivity_plus: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/logo.jpg"
  adaptive_icon_background: "#FFEBEE"
  adaptive_icon_foreground: "assets/icon/logo_foreground.png"

flutter:
  uses-material-design: true
  assets:
    - assets/blood_banks.json
    - assets/images/
    - assets/icon/
